title: **Atharva's AI Blog**
email: atharva.musale@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  AI enthusiast on the journey to find perfectly optimized models :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AtharvaMusale
github_username:  AtharvaMusale

# Build settings
theme: minima
plugins:
  - jekyll-feed



markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
